# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import fasttextserver_pb2 as fasttextserver__pb2


class FasttextStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.WordEmbedding = channel.unary_unary(
        '/nlp.Fasttext/WordEmbedding',
        request_serializer=fasttextserver__pb2.SentenceRequest.SerializeToString,
        response_deserializer=fasttextserver__pb2.WordEmbeddingResponse.FromString,
        )
    self.MultiWordEmbeddings = channel.unary_unary(
        '/nlp.Fasttext/MultiWordEmbeddings',
        request_serializer=fasttextserver__pb2.MultiSentencesRequest.SerializeToString,
        response_deserializer=fasttextserver__pb2.MultiWordEmbeddingsResponse.FromString,
        )
    self.SentenceEmbedding = channel.unary_unary(
        '/nlp.Fasttext/SentenceEmbedding',
        request_serializer=fasttextserver__pb2.SentenceRequest.SerializeToString,
        response_deserializer=fasttextserver__pb2.SentenceEmbeddingResponse.FromString,
        )
    self.Predict = channel.unary_unary(
        '/nlp.Fasttext/Predict',
        request_serializer=fasttextserver__pb2.SentenceRequest.SerializeToString,
        response_deserializer=fasttextserver__pb2.PredictResponse.FromString,
        )
    self.Reload = channel.unary_unary(
        '/nlp.Fasttext/Reload',
        request_serializer=fasttextserver__pb2.ReloadRequest.SerializeToString,
        response_deserializer=fasttextserver__pb2.Response.FromString,
        )


class FasttextServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def WordEmbedding(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MultiWordEmbeddings(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SentenceEmbedding(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Predict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Reload(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FasttextServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'WordEmbedding': grpc.unary_unary_rpc_method_handler(
          servicer.WordEmbedding,
          request_deserializer=fasttextserver__pb2.SentenceRequest.FromString,
          response_serializer=fasttextserver__pb2.WordEmbeddingResponse.SerializeToString,
      ),
      'MultiWordEmbeddings': grpc.unary_unary_rpc_method_handler(
          servicer.MultiWordEmbeddings,
          request_deserializer=fasttextserver__pb2.MultiSentencesRequest.FromString,
          response_serializer=fasttextserver__pb2.MultiWordEmbeddingsResponse.SerializeToString,
      ),
      'SentenceEmbedding': grpc.unary_unary_rpc_method_handler(
          servicer.SentenceEmbedding,
          request_deserializer=fasttextserver__pb2.SentenceRequest.FromString,
          response_serializer=fasttextserver__pb2.SentenceEmbeddingResponse.SerializeToString,
      ),
      'Predict': grpc.unary_unary_rpc_method_handler(
          servicer.Predict,
          request_deserializer=fasttextserver__pb2.SentenceRequest.FromString,
          response_serializer=fasttextserver__pb2.PredictResponse.SerializeToString,
      ),
      'Reload': grpc.unary_unary_rpc_method_handler(
          servicer.Reload,
          request_deserializer=fasttextserver__pb2.ReloadRequest.FromString,
          response_serializer=fasttextserver__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'nlp.Fasttext', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
