# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fasttextserver.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fasttextserver.proto',
  package='nlp',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x66\x61sttextserver.proto\x12\x03nlp\"E\n\x0fSentenceRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0f\n\x07spacing\x18\x03 \x01(\x08\"L\n\x15MultiSentencesRequest\x12\x11\n\tsentences\x18\x01 \x03(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0f\n\x07spacing\x18\x03 \x01(\x08\":\n\x15WordEmbeddingResponse\x12\x12\n\nembeddings\x18\x01 \x03(\x02\x12\r\n\x05words\x18\x02 \x03(\t\"H\n\x1bMultiWordEmbeddingsResponse\x12)\n\x05items\x18\x01 \x03(\x0b\x32\x1a.nlp.WordEmbeddingResponse\"/\n\x19SentenceEmbeddingResponse\x12\x12\n\nembeddings\x18\x01 \x03(\x02\"F\n\rReloadRequest\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x10\n\x08\x66ilepath\x18\x03 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"S\n\x0ePredictRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0f\n\x07spacing\x18\x03 \x01(\x08\x12\r\n\x05limit\x18\x04 \x01(\x05\"0\n\x0fPredictResponse\x12\x0e\n\x06labels\x18\x01 \x03(\t\x12\r\n\x05probs\x18\x02 \x03(\x02\x32\xda\x02\n\x08\x46\x61sttext\x12\x43\n\rWordEmbedding\x12\x14.nlp.SentenceRequest\x1a\x1a.nlp.WordEmbeddingResponse\"\x00\x12U\n\x13MultiWordEmbeddings\x12\x1a.nlp.MultiSentencesRequest\x1a .nlp.MultiWordEmbeddingsResponse\"\x00\x12K\n\x11SentenceEmbedding\x12\x14.nlp.SentenceRequest\x1a\x1e.nlp.SentenceEmbeddingResponse\"\x00\x12\x36\n\x07Predict\x12\x13.nlp.PredictRequest\x1a\x14.nlp.PredictResponse\"\x00\x12-\n\x06Reload\x12\x12.nlp.ReloadRequest\x1a\r.nlp.Response\"\x00\x62\x06proto3')
)




_SENTENCEREQUEST = _descriptor.Descriptor(
  name='SentenceRequest',
  full_name='nlp.SentenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='nlp.SentenceRequest.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='nlp.SentenceRequest.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spacing', full_name='nlp.SentenceRequest.spacing', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=98,
)


_MULTISENTENCESREQUEST = _descriptor.Descriptor(
  name='MultiSentencesRequest',
  full_name='nlp.MultiSentencesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentences', full_name='nlp.MultiSentencesRequest.sentences', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='nlp.MultiSentencesRequest.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spacing', full_name='nlp.MultiSentencesRequest.spacing', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=176,
)


_WORDEMBEDDINGRESPONSE = _descriptor.Descriptor(
  name='WordEmbeddingResponse',
  full_name='nlp.WordEmbeddingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='embeddings', full_name='nlp.WordEmbeddingResponse.embeddings', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='words', full_name='nlp.WordEmbeddingResponse.words', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=236,
)


_MULTIWORDEMBEDDINGSRESPONSE = _descriptor.Descriptor(
  name='MultiWordEmbeddingsResponse',
  full_name='nlp.MultiWordEmbeddingsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='nlp.MultiWordEmbeddingsResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=310,
)


_SENTENCEEMBEDDINGRESPONSE = _descriptor.Descriptor(
  name='SentenceEmbeddingResponse',
  full_name='nlp.SentenceEmbeddingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='embeddings', full_name='nlp.SentenceEmbeddingResponse.embeddings', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=359,
)


_RELOADREQUEST = _descriptor.Descriptor(
  name='ReloadRequest',
  full_name='nlp.ReloadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_type', full_name='nlp.ReloadRequest.model_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='nlp.ReloadRequest.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filepath', full_name='nlp.ReloadRequest.filepath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=431,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='nlp.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='nlp.Response.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=460,
)


_PREDICTREQUEST = _descriptor.Descriptor(
  name='PredictRequest',
  full_name='nlp.PredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='nlp.PredictRequest.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='nlp.PredictRequest.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spacing', full_name='nlp.PredictRequest.spacing', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit', full_name='nlp.PredictRequest.limit', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=545,
)


_PREDICTRESPONSE = _descriptor.Descriptor(
  name='PredictResponse',
  full_name='nlp.PredictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='nlp.PredictResponse.labels', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='probs', full_name='nlp.PredictResponse.probs', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=595,
)

_MULTIWORDEMBEDDINGSRESPONSE.fields_by_name['items'].message_type = _WORDEMBEDDINGRESPONSE
DESCRIPTOR.message_types_by_name['SentenceRequest'] = _SENTENCEREQUEST
DESCRIPTOR.message_types_by_name['MultiSentencesRequest'] = _MULTISENTENCESREQUEST
DESCRIPTOR.message_types_by_name['WordEmbeddingResponse'] = _WORDEMBEDDINGRESPONSE
DESCRIPTOR.message_types_by_name['MultiWordEmbeddingsResponse'] = _MULTIWORDEMBEDDINGSRESPONSE
DESCRIPTOR.message_types_by_name['SentenceEmbeddingResponse'] = _SENTENCEEMBEDDINGRESPONSE
DESCRIPTOR.message_types_by_name['ReloadRequest'] = _RELOADREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['PredictRequest'] = _PREDICTREQUEST
DESCRIPTOR.message_types_by_name['PredictResponse'] = _PREDICTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SentenceRequest = _reflection.GeneratedProtocolMessageType('SentenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENTENCEREQUEST,
  '__module__' : 'fasttextserver_pb2'
  # @@protoc_insertion_point(class_scope:nlp.SentenceRequest)
  })
_sym_db.RegisterMessage(SentenceRequest)

MultiSentencesRequest = _reflection.GeneratedProtocolMessageType('MultiSentencesRequest', (_message.Message,), {
  'DESCRIPTOR' : _MULTISENTENCESREQUEST,
  '__module__' : 'fasttextserver_pb2'
  # @@protoc_insertion_point(class_scope:nlp.MultiSentencesRequest)
  })
_sym_db.RegisterMessage(MultiSentencesRequest)

WordEmbeddingResponse = _reflection.GeneratedProtocolMessageType('WordEmbeddingResponse', (_message.Message,), {
  'DESCRIPTOR' : _WORDEMBEDDINGRESPONSE,
  '__module__' : 'fasttextserver_pb2'
  # @@protoc_insertion_point(class_scope:nlp.WordEmbeddingResponse)
  })
_sym_db.RegisterMessage(WordEmbeddingResponse)

MultiWordEmbeddingsResponse = _reflection.GeneratedProtocolMessageType('MultiWordEmbeddingsResponse', (_message.Message,), {
  'DESCRIPTOR' : _MULTIWORDEMBEDDINGSRESPONSE,
  '__module__' : 'fasttextserver_pb2'
  # @@protoc_insertion_point(class_scope:nlp.MultiWordEmbeddingsResponse)
  })
_sym_db.RegisterMessage(MultiWordEmbeddingsResponse)

SentenceEmbeddingResponse = _reflection.GeneratedProtocolMessageType('SentenceEmbeddingResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENTENCEEMBEDDINGRESPONSE,
  '__module__' : 'fasttextserver_pb2'
  # @@protoc_insertion_point(class_scope:nlp.SentenceEmbeddingResponse)
  })
_sym_db.RegisterMessage(SentenceEmbeddingResponse)

ReloadRequest = _reflection.GeneratedProtocolMessageType('ReloadRequest', (_message.Message,), {
  'DESCRIPTOR' : _RELOADREQUEST,
  '__module__' : 'fasttextserver_pb2'
  # @@protoc_insertion_point(class_scope:nlp.ReloadRequest)
  })
_sym_db.RegisterMessage(ReloadRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'fasttextserver_pb2'
  # @@protoc_insertion_point(class_scope:nlp.Response)
  })
_sym_db.RegisterMessage(Response)

PredictRequest = _reflection.GeneratedProtocolMessageType('PredictRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTREQUEST,
  '__module__' : 'fasttextserver_pb2'
  # @@protoc_insertion_point(class_scope:nlp.PredictRequest)
  })
_sym_db.RegisterMessage(PredictRequest)

PredictResponse = _reflection.GeneratedProtocolMessageType('PredictResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTRESPONSE,
  '__module__' : 'fasttextserver_pb2'
  # @@protoc_insertion_point(class_scope:nlp.PredictResponse)
  })
_sym_db.RegisterMessage(PredictResponse)



_FASTTEXT = _descriptor.ServiceDescriptor(
  name='Fasttext',
  full_name='nlp.Fasttext',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=598,
  serialized_end=944,
  methods=[
  _descriptor.MethodDescriptor(
    name='WordEmbedding',
    full_name='nlp.Fasttext.WordEmbedding',
    index=0,
    containing_service=None,
    input_type=_SENTENCEREQUEST,
    output_type=_WORDEMBEDDINGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MultiWordEmbeddings',
    full_name='nlp.Fasttext.MultiWordEmbeddings',
    index=1,
    containing_service=None,
    input_type=_MULTISENTENCESREQUEST,
    output_type=_MULTIWORDEMBEDDINGSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SentenceEmbedding',
    full_name='nlp.Fasttext.SentenceEmbedding',
    index=2,
    containing_service=None,
    input_type=_SENTENCEREQUEST,
    output_type=_SENTENCEEMBEDDINGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='nlp.Fasttext.Predict',
    index=3,
    containing_service=None,
    input_type=_PREDICTREQUEST,
    output_type=_PREDICTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Reload',
    full_name='nlp.Fasttext.Reload',
    index=4,
    containing_service=None,
    input_type=_RELOADREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FASTTEXT)

DESCRIPTOR.services_by_name['Fasttext'] = _FASTTEXT

# @@protoc_insertion_point(module_scope)
