# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import fasttextserver_pb2 as fasttextserver__pb2


class FasttextStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.WordEmbedding = channel.unary_unary(
        '/fasttextserver.Fasttext/WordEmbedding',
        request_serializer=fasttextserver__pb2.WordEmbeddingRequest.SerializeToString,
        response_deserializer=fasttextserver__pb2.WordEmbeddingResponse.FromString,
        )


class FasttextServicer(object):
  """The greeting service definition.
  """

  def WordEmbedding(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FasttextServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'WordEmbedding': grpc.unary_unary_rpc_method_handler(
          servicer.WordEmbedding,
          request_deserializer=fasttextserver__pb2.WordEmbeddingRequest.FromString,
          response_serializer=fasttextserver__pb2.WordEmbeddingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fasttextserver.Fasttext', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
