#!/bin/bash
source config.sh
echo "container_name: $CONTAINER_NAME"
echo "port: $PORT"

MODEL=models2

mkdir -p $MODEL
mkdir -p log

docker run --rm -d --name $CONTAINER_NAME -it -p $PORT:50051 \
  -v "$(pwd)":/app \
  --volumes-from aws-config \
  daangn/fasttext-server:v20190808 server.py --log="log/${CONTAINER_NAME}.log" \
    --debug --spacing-model-path='' --model-path $MODEL
    #--s3-model-path s3://daangn/ml/fasttext-server/models \
  #-v "$(pwd)/log":/app/log \
  #-v "$(pwd)/$MODEL":/app/models \
